name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_AZURE_USER}}/api .
    - name: Copying docker tag
      run: docker tag ${{secrets.DOCKER_AZURE_USER}}/api ${{secrets.DOCKER_AZURE_USER}}.azurecr.io/api
    - name: Docker auth
      run: docker login --username ${{secrets.DOCKER_AZURE_USER}} --password ${{secrets.DOCKER_AZURE_PASSWORD}}
